fix(cicd): Disable exit on error for critical function

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -108,12 +108,19 @@ jobs:
             git add .
             git commit -a -m "chore([skip ci]): Action ${{ github.run_number }}: ${{ matrix.versions }} bumps"
             
+            # Compute push
             versions_against=$(echo '${{ needs.determine-versions.outputs.versions }}' | jq '. | length')
             MAX_RETRIES=$((versions_against * 5))
             count=0
+          
+            # Handle if exit on error
+            set +e
+          
             until git push --force-with-lease -u origin ${{ github.ref_name }} || [ $count -eq $MAX_RETRIES ]; do
               ((count++))
               git fetch
               git merge -X theirs
             done
+          
+            set -e
           fi
